language: cpp
sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y -qq g++-8
  - sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script: 
  - make
  