language: cpp
dist: xenial
  
matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y -qq g++-8
        - sudo apt-get install -y --no-install-recommends make libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      script: 
        - make CC=$CC CXX=$CXX
    - os: linux
      compiler: clang
      before_install:
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y --no-install-recommends make libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
      script: 
        - make CC=$CC CXX=$CXX
    - os: windows
      compiler: gcc
      script:
        - mingw32-make CC=$CC CXX=$CXX
    - os: windows
      compiler: msvc
      script:
        - echo $PATH
        - ls "/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
